### ISSUE TITLE
Do not store tokens in any DB or cache

### ISSUE THREAD

**Issue by grubastik** [bliuchak/auth#5]
Userstory for retrieving token:
1. User send auth request with correct login and password.
2. Server verify user and generate token which includes userID and email.
3. Server sign token with key.

User story for verifying token:
1. On each request except auth, register, version, health, server must get auth token and send it to validation.
2. validation endpoint should:
2.1 validate token signature
2.2 check for expiration
2.3 check if token contains valid user information
2.4 if previous validation passed successfully return true, otherwise false

User story for reissuing token:
1. to reissue token server should get valid token.
2. server perform validation of token.
3. server create new token with new signature and new expiration.

**Comment by bliuchak** [comment]
"User story for retrieving token" - implemented in `login` endpoint
"User story for verifying token" - prepared in middleware `JWTValidation()`
"User story for reissuing token" - implemented in `refresh` endpoint

See #9

**Comment by bliuchak** [comment]
Implemented
